#!/bin/bash

# Create temp suppression file
cat > /tmp/readline.supp << EOF
{
   leak readline
   Memcheck:Leak
   match-leak-kinds: definite,possible,reachable,indirect
   ...
   fun:readline
}
{
   leak add_history
   Memcheck:Leak
   match-leak-kinds: definite,possible,reachable,indirect
   ...
   fun:add_history
}
{
   leak readline_internal
   Memcheck:Leak
   match-leak-kinds: definite,possible,reachable,indirect
   ...
   fun:readline_internal_setup
}
{
   leak rl_init
   Memcheck:Leak
   match-leak-kinds: definite,possible,reachable,indirect
   ...
   fun:rl_initialize
}
EOF

# Run valgrind with the suppression file
valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --track-fds=yes --suppressions=/tmp/readline.supp "$@"
